[package]
name = "rustbuster"
version = "0.1.0"
authors = ["John <jgbstephenson@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap="2.33.3"
reqwest = { version = "0.10.8", features=["blocking"] }
